### ISSUE TITLE
MailDataManager breaks the transaction manager upon abort

### ISSUE THREAD

**Issue by mmerickel** [repoze/repoze.sendmail#31]
I have some code sending emails and for legitimate reasons the email is rejected by the remote server. I want to log the exception but instead I see the `ValueError('TPC in progress')` a couple times in the output, squashing the error.

It's actually causing the transaction manager to be in such a broken state that the next transaction.manager.begin() after the failed abort, causes another exception. Below is the crap fix to prove the diagnosis, but I'm not positive it's the correct fix. I downgraded to 4.1 and things work as expected.

From what I can tell this behavior appeared in https://github.com/repoze/repoze.sendmail/commit/06ad882dc4f4a220fba2583e67076e9f3dcf3359 when the manager was rewritten.

On a related side note, aborting in the second phase of a two-phase commit is a Really Bad Thing(tm). Since sending email isn't transactional it almost makes more sense to either send the email in an earlier phase or even as an `afterCommitHook`.

``` diff
diff --git a/repoze/sendmail/delivery.py b/repoze/sendmail/delivery.py
index 59115d7..6b56add 100644
--- a/repoze/sendmail/delivery.py
+++ b/repoze/sendmail/delivery.py
@@ -115,8 +115,8 @@ class MailDataManager(object):
             raise ValueError("Not in a transaction")
         if self.transaction is not trans:
             raise ValueError("In a different transaction")
-        if self.tpc_phase != 0:
-            raise ValueError("TPC in progress")
+        #if self.tpc_phase != 0:
+        #    raise ValueError("TPC in progress")
         if self.onAbort:
             self.onAbort()
```

**Comment by ctheune** [comment]
Interesting. I'm stumbling over a "domain not found" and I really don't care. Downgrading to 4.1 doesn't fix it. This ends up in half-deliveries :(

**Comment by ctheune** [comment]
From what I can see the most reasonable part would be to bare-except the send() method completely: in the special case of email, I don't see why uncontrollably failing the whole transaction is better than to best-effort this. This is email anyway. We _could_ do better if the data manager would have more control over the whole process and move some of the communication to the first phase (like rcpt, or other stuff).

**Comment by vietdt** [comment]
After struggling to debug this issue (and also related issue [#30](https://github.com/repoze/repoze.sendmail/issues/30)), I think the best and simplest approach is to reset the "tpc_phase" value to 0 after a two-phase commit completely finished or aborted. It then will not fail any later transaction.abort() calls. So both issues would be resolved.

I've implemented my fix in a fork https://github.com/vietdt/repoze.sendmail/commit/aba1cc583edf4be0c6e3c5f3218fe97c55baffec. Not sure if it works and could be merged upstream.
```
diff --git a/repoze/sendmail/delivery.py b/repoze/sendmail/delivery.py
index 59115d7..28b7cf4 100644
--- a/repoze/sendmail/delivery.py
+++ b/repoze/sendmail/delivery.py
@@ -102,6 +102,7 @@ class MailDataManager(object):
         if self.transaction is None:
             raise ValueError("Not in a transaction")
         self.state = final_state
+        self.tpc_phase = 0
 
     def commit(self, trans):
         if self.transaction is None:
```
Also found the same implementation in a test script in transaction package
https://github.com/zopefoundation/transaction/blob/master/transaction/tests/savepointsample.py#L95-L98

**Comment by tseaver** [comment]
@vietdt Your suggested fix looks correct to me.  @mmerickel can you test it against your failing case?

**Comment by vietdt** [comment]
@tseaver it seems there's no response from @mmerickel. Could anyone help on testing to confirm the fix? If the fix is correct, I would like to use it from mainstream package rather than from a fork or have to pin to version 4.1.

**Comment by papachoco** [comment]
Will there be a 4.3 release w/ the fix for this issue?
